---
namespace: nicholaswilde
name: flux
version: 0.1.0
readme: README.md
authors:
  - Nicholas Wilde (github.com/nicholaswilde)
description: A collection of Flux roles for Ansible.
license_file: LICENSE
tags:
  - flux
  - gitops
  - fluxcd
  - fluxctl
repository: https://github.com/nicholaswilde/ansible-collection-flux
homepage: https://github.com/nicholaswilde/ansible-collection-flux
issues: https://github.com/nicholaswilde/ansible-collection-flux/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
